### ISSUE TITLE
Does this work with Selects, Radios, or Checkboxes

### ISSUE THREAD

**Issue by jesseschutt** [cfurrow/jquery.autosave.js#2]
Thank you for putting this code together! It's just what I'm needing for a project. 

Out of curiosity, is it possible to make this work with Selects, Radios, or Checkboxes?

**Comment by cfurrow** [comment]
Yes, since it responds to the `change` event, any element that fires that would be able to use this plugin.

**Comment by jesseschutt** [comment]
Thanks Carl - I have Selects responding, but I can't seem to get Radios or Checkboxes responding to the change event. Can you see anything wrong with the following?

``` javascript
$("input, select, textarea, input:checkbox, input:radio").autosave({
        url:"/",
        event:"change",
        type: "json",
        debug: true,
        before:beforeCallback,
        success:successCallback
    });
```
